/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  published?: boolean | null;
  contentBlocks?:
    | (
        | {
            announcement?: {
              text?: string | null;
              href?: string | null;
            };
            heading?: string | null;
            description?: string | null;
            primaryCta: {
              label: string;
              href: string;
            };
            secondaryCta: {
              label: string;
              href: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSimpleCentered';
          }
        | {
            companyName?: string | null;
            logo?: {
              light?: (number | null) | Media;
              dark?: (number | null) | Media;
            };
            badge?: {
              text?: string | null;
              link?: string | null;
            };
            heading?: string | null;
            description?: string | null;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            heroImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSplitWithImage';
          }
        | {
            heading?: string | null;
            description?: string | null;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            heroImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSplitWithImageAngled';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            button?: {
              label?: string | null;
              href?: string | null;
            };
            subAction?: {
              label?: string | null;
              href?: string | null;
            };
            images?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroWithOffsetImg';
          }
        | {
            heading?: string | null;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headingSimpleLeft';
          }
        | {
            backgroundImage?: {
              light?: (number | null) | Media;
              dark?: (number | null) | Media;
            };
            title?: string | null;
            description?: string | null;
            links?:
              | {
                  label: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headingWithStats';
          }
        | {
            lightImage: {
              src: number | Media;
              alt?: string | null;
            };
            darkImage: {
              src: number | Media;
              alt?: string | null;
            };
            heading?: string | null;
            description?: string | null;
            cards?:
              | {
                  iconSvg: string;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headingWithCards';
          }
        | {
            topCaption?: string | null;
            title: string;
            subtitle?: string | null;
            columns: {
              icon?: string | null;
              title: string;
              caption?: string | null;
              action?: {
                label?: string | null;
                href?: string | null;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'featSimpleThreeCol';
          }
        | {
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsSimple';
          }
        | {
            heading?: string | null;
            description?: string | null;
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsSimpleGrid';
          }
        | {
            lightImage: {
              src: number | Media;
              alt?: string | null;
            };
            darkImage: {
              src: number | Media;
              alt?: string | null;
            };
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsWithBg';
          }
        | {
            image: {
              src: number | Media;
              alt?: string | null;
            };
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsSplitWithImg';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            descriptionColumns?:
              | {
                  paragraphs?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsTwoColDesc';
          }
        | {
            heading?: string | null;
            leadText?: string | null;
            bodyText?: string | null;
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsWithDesc';
          }
        | {
            heading?: string | null;
            description?: string | null;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaCenteredPanel';
          }
        | {
            heading?: string | null;
            description?: string | null;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaCenteredPlain';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            description?: string | null;
            cta?: {
              label?: string | null;
              href?: string | null;
            };
            images?:
              | {
                  src: number | Media;
                  alt?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaImageTiles';
          }
        | {
            heading?: string | null;
            description?: string | null;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaSimpleCenteredGradient';
          }
        | {
            badge?: string | null;
            heading?: string | null;
            description?: string | null;
            cta?: {
              label?: string | null;
              href?: string | null;
            };
            image?: {
              src?: (number | null) | Media;
              alt?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaSplitWithImage';
          }
        | {
            heading?: string | null;
            description?: string | null;
            items?:
              | {
                  title: string;
                  description: string;
                  linkLabel: string;
                  linkHref: string;
                  /**
                   * Paste raw SVG markup. Must include class="size-6 text-white" on the root element.
                   */
                  iconSvg?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactSimpleCentered';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            offices?:
              | {
                  name: string;
                  lines: {
                    line: string;
                    id?: string | null;
                  }[];
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactSimpleFourCol';
          }
        | {
            heading?: string | null;
            description?: string | null;
            address?: {
              label?: string | null;
              html?: string | null;
            };
            phone?: {
              label?: string | null;
              text?: string | null;
              href?: string | null;
            };
            email?: {
              label?: string | null;
              text?: string | null;
              href?: string | null;
            };
            form?: {
              action?: string | null;
              submitLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactSplitWithForm';
          }
        | {
            heading?: string | null;
            description?: string | null;
            emailPlaceholder?: string | null;
            subscribeLabel?: string | null;
            features?:
              | {
                  iconSvg: string;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletterWithDetails';
          }
        | {
            heading?: string | null;
            emailPlaceholder?: string | null;
            subscribeLabel?: string | null;
            privacyText?: string | null;
            privacyLink?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletterSimple';
          }
        | {
            heading?: string | null;
            emailPlaceholder?: string | null;
            subscribeLabel?: string | null;
            privacyText?: string | null;
            privacyLink?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletterSimpleStacked';
          }
        | {
            errorCode?: string | null;
            heading?: string | null;
            description?: string | null;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'notFoundSimple';
          }
        | {
            companyName?: string | null;
            logo?: {
              light?: (number | null) | Media;
              dark?: (number | null) | Media;
              href?: string | null;
            };
            errorCode?: string | null;
            heading?: string | null;
            description?: string | null;
            back?: {
              label?: string | null;
              href?: string | null;
            };
            footerLinks?:
              | {
                  label: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            backgroundImage?: {
              light?: (number | null) | Media;
              dark?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'notFoundImageSplit';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  published?: T;
  contentBlocks?:
    | T
    | {
        heroSimpleCentered?:
          | T
          | {
              announcement?:
                | T
                | {
                    text?: T;
                    href?: T;
                  };
              heading?: T;
              description?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heroSplitWithImage?:
          | T
          | {
              companyName?: T;
              logo?:
                | T
                | {
                    light?: T;
                    dark?: T;
                  };
              badge?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              heading?: T;
              description?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              heroImage?: T;
              id?: T;
              blockName?: T;
            };
        heroSplitWithImageAngled?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              heroImage?: T;
              id?: T;
              blockName?: T;
            };
        heroWithOffsetImg?:
          | T
          | {
              title?: T;
              subtitle?: T;
              button?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              subAction?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        headingSimpleLeft?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        headingWithStats?:
          | T
          | {
              backgroundImage?:
                | T
                | {
                    light?: T;
                    dark?: T;
                  };
              title?: T;
              description?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        headingWithCards?:
          | T
          | {
              lightImage?:
                | T
                | {
                    src?: T;
                    alt?: T;
                  };
              darkImage?:
                | T
                | {
                    src?: T;
                    alt?: T;
                  };
              heading?: T;
              description?: T;
              cards?:
                | T
                | {
                    iconSvg?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featSimpleThreeCol?:
          | T
          | {
              topCaption?: T;
              title?: T;
              subtitle?: T;
              columns?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    caption?: T;
                    action?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsSimple?:
          | T
          | {
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsSimpleGrid?:
          | T
          | {
              heading?: T;
              description?: T;
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsWithBg?:
          | T
          | {
              lightImage?:
                | T
                | {
                    src?: T;
                    alt?: T;
                  };
              darkImage?:
                | T
                | {
                    src?: T;
                    alt?: T;
                  };
              eyebrow?: T;
              heading?: T;
              description?: T;
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsSplitWithImg?:
          | T
          | {
              image?:
                | T
                | {
                    src?: T;
                    alt?: T;
                  };
              eyebrow?: T;
              heading?: T;
              description?: T;
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsTwoColDesc?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              descriptionColumns?:
                | T
                | {
                    paragraphs?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsWithDesc?:
          | T
          | {
              heading?: T;
              leadText?: T;
              bodyText?: T;
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaCenteredPanel?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaCenteredPlain?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaImageTiles?:
          | T
          | {
              heading?: T;
              subheading?: T;
              description?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              images?:
                | T
                | {
                    src?: T;
                    alt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaSimpleCenteredGradient?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaSplitWithImage?:
          | T
          | {
              badge?: T;
              heading?: T;
              description?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              image?:
                | T
                | {
                    src?: T;
                    alt?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactSimpleCentered?:
          | T
          | {
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    linkLabel?: T;
                    linkHref?: T;
                    iconSvg?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactSimpleFourCol?:
          | T
          | {
              title?: T;
              subtitle?: T;
              offices?:
                | T
                | {
                    name?: T;
                    lines?:
                      | T
                      | {
                          line?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactSplitWithForm?:
          | T
          | {
              heading?: T;
              description?: T;
              address?:
                | T
                | {
                    label?: T;
                    html?: T;
                  };
              phone?:
                | T
                | {
                    label?: T;
                    text?: T;
                    href?: T;
                  };
              email?:
                | T
                | {
                    label?: T;
                    text?: T;
                    href?: T;
                  };
              form?:
                | T
                | {
                    action?: T;
                    submitLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletterWithDetails?:
          | T
          | {
              heading?: T;
              description?: T;
              emailPlaceholder?: T;
              subscribeLabel?: T;
              features?:
                | T
                | {
                    iconSvg?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletterSimple?:
          | T
          | {
              heading?: T;
              emailPlaceholder?: T;
              subscribeLabel?: T;
              privacyText?: T;
              privacyLink?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletterSimpleStacked?:
          | T
          | {
              heading?: T;
              emailPlaceholder?: T;
              subscribeLabel?: T;
              privacyText?: T;
              privacyLink?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        notFoundSimple?:
          | T
          | {
              errorCode?: T;
              heading?: T;
              description?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        notFoundImageSplit?:
          | T
          | {
              companyName?: T;
              logo?:
                | T
                | {
                    light?: T;
                    dark?: T;
                    href?: T;
                  };
              errorCode?: T;
              heading?: T;
              description?: T;
              back?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              footerLinks?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              backgroundImage?:
                | T
                | {
                    light?: T;
                    dark?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}