/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  published?: boolean | null;
  contentBlocks?:
    | (
        | {
            announcement?: {
              text?: string | null;
              href?: string | null;
            };
            heading?: string | null;
            description?: string | null;
            primaryCta: {
              label: string;
              href: string;
            };
            secondaryCta: {
              label: string;
              href: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSimpleCentered';
          }
        | {
            companyName?: string | null;
            logoLight?: (number | null) | Media;
            logoDark?: (number | null) | Media;
            badge?: {
              text?: string | null;
              link?: string | null;
            };
            heading?: string | null;
            description?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            heroImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSplitWithImage';
          }
        | {
            heading?: string | null;
            description?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            heroImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSplitWithImageAngled';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            buttonLabel?: string | null;
            buttonHref?: string | null;
            subActionLabel?: string | null;
            subActionHref?: string | null;
            images?:
              | {
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroWithOffsetImg';
          }
        | {
            logo?: {
              image?: (number | null) | Media;
              darkImage?: (number | null) | Media;
              companyName?: string | null;
            };
            navLinks?:
              | {
                  label: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            login?: {
              label?: string | null;
              href?: string | null;
            };
            heading?: string | null;
            description?: string | null;
            primaryCta: {
              label: string;
              href: string;
            };
            secondaryCta: {
              label: string;
              href: string;
            };
            galleryCol1Images?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            galleryCol2Images?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            galleryCol3Images?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroWithOffsetImgV2';
          }
        | {
            heading?: string | null;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headingSimpleLeft';
          }
        | {
            lightBgImage?: (number | null) | Media;
            darkBgImage?: (number | null) | Media;
            title?: string | null;
            description?: string | null;
            links?:
              | {
                  label: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headingWithStats';
          }
        | {
            lightImage?: (number | null) | Media;
            lightImageAlt?: string | null;
            darkImage?: (number | null) | Media;
            darkImageAlt?: string | null;
            heading?: string | null;
            description?: string | null;
            cards?:
              | {
                  iconSvg?: string | null;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headingWithCards';
          }
        | {
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsSimple';
          }
        | {
            heading?: string | null;
            description?: string | null;
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsSimpleGrid';
          }
        | {
            lightImage?: (number | null) | Media;
            lightImageAlt?: string | null;
            darkImage?: (number | null) | Media;
            darkImageAlt?: string | null;
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsWithBg';
          }
        | {
            image?: (number | null) | Media;
            imageAlt?: string | null;
            eyebrow?: string | null;
            heading?: string | null;
            description?: string | null;
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsSplitWithImg';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            descriptionColumns?:
              | {
                  paragraphs?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsTwoColDesc';
          }
        | {
            heading?: string | null;
            leadText?: string | null;
            bodyText?: string | null;
            stats?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsWithDesc';
          }
        | {
            heading?: string | null;
            description?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaCenteredPanel';
          }
        | {
            heading?: string | null;
            description?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaCenteredPlain';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            description?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            images?:
              | {
                  image?: (number | null) | Media;
                  alt?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaImageTiles';
          }
        | {
            heading?: string | null;
            description?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaSimpleCenteredGradient';
          }
        | {
            badge?: string | null;
            heading?: string | null;
            description?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            image?: (number | null) | Media;
            imageAlt?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaSplitWithImage';
          }
        | {
            heading?: string | null;
            description?: string | null;
            items?:
              | {
                  title: string;
                  description: string;
                  linkLabel: string;
                  linkHref: string;
                  iconSvg?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactSimpleCentered';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            offices?:
              | {
                  name: string;
                  lines?:
                    | {
                        line: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactSimpleFourCol';
          }
        | {
            heading?: string | null;
            description?: string | null;
            addressLabel?: string | null;
            addressHtml?: string | null;
            phoneLabel?: string | null;
            phoneText?: string | null;
            phoneHref?: string | null;
            emailLabel?: string | null;
            emailText?: string | null;
            emailHref?: string | null;
            formAction?: string | null;
            submitLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactSplitWithForm';
          }
        | {
            heading?: string | null;
            description?: string | null;
            emailPlaceholder?: string | null;
            subscribeLabel?: string | null;
            features?:
              | {
                  iconSvg?: string | null;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletterWithDetails';
          }
        | {
            heading?: string | null;
            emailPlaceholder?: string | null;
            subscribeLabel?: string | null;
            privacyText?: string | null;
            privacyLinkLabel?: string | null;
            privacyLinkHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletterSimple';
          }
        | {
            heading?: string | null;
            emailPlaceholder?: string | null;
            subscribeLabel?: string | null;
            privacyText?: string | null;
            privacyLinkLabel?: string | null;
            privacyLinkHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletterSimpleStacked';
          }
        | {
            errorCode?: string | null;
            heading?: string | null;
            description?: string | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'notFoundSimple';
          }
        | {
            companyName?: string | null;
            logoLight?: (number | null) | Media;
            logoDark?: (number | null) | Media;
            logoHref?: string | null;
            errorCode?: string | null;
            heading?: string | null;
            description?: string | null;
            backLabel?: string | null;
            backHref?: string | null;
            footerLinks?:
              | {
                  label: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            backgroundImageLight?: (number | null) | Media;
            backgroundImageDark?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'notFoundImageSplit';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  published?: T;
  contentBlocks?:
    | T
    | {
        heroSimpleCentered?:
          | T
          | {
              announcement?:
                | T
                | {
                    text?: T;
                    href?: T;
                  };
              heading?: T;
              description?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heroSplitWithImage?:
          | T
          | {
              companyName?: T;
              logoLight?: T;
              logoDark?: T;
              badge?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              heading?: T;
              description?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              heroImage?: T;
              id?: T;
              blockName?: T;
            };
        heroSplitWithImageAngled?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              heroImage?: T;
              id?: T;
              blockName?: T;
            };
        heroWithOffsetImg?:
          | T
          | {
              title?: T;
              subtitle?: T;
              buttonLabel?: T;
              buttonHref?: T;
              subActionLabel?: T;
              subActionHref?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heroWithOffsetImgV2?:
          | T
          | {
              logo?:
                | T
                | {
                    image?: T;
                    darkImage?: T;
                    companyName?: T;
                  };
              navLinks?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              login?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              heading?: T;
              description?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              galleryCol1Images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              galleryCol2Images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              galleryCol3Images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        headingSimpleLeft?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        headingWithStats?:
          | T
          | {
              lightBgImage?: T;
              darkBgImage?: T;
              title?: T;
              description?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        headingWithCards?:
          | T
          | {
              lightImage?: T;
              lightImageAlt?: T;
              darkImage?: T;
              darkImageAlt?: T;
              heading?: T;
              description?: T;
              cards?:
                | T
                | {
                    iconSvg?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsSimple?:
          | T
          | {
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsSimpleGrid?:
          | T
          | {
              heading?: T;
              description?: T;
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsWithBg?:
          | T
          | {
              lightImage?: T;
              lightImageAlt?: T;
              darkImage?: T;
              darkImageAlt?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsSplitWithImg?:
          | T
          | {
              image?: T;
              imageAlt?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsTwoColDesc?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              descriptionColumns?:
                | T
                | {
                    paragraphs?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsWithDesc?:
          | T
          | {
              heading?: T;
              leadText?: T;
              bodyText?: T;
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaCenteredPanel?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              id?: T;
              blockName?: T;
            };
        ctaCenteredPlain?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              id?: T;
              blockName?: T;
            };
        ctaImageTiles?:
          | T
          | {
              heading?: T;
              subheading?: T;
              description?: T;
              ctaLabel?: T;
              ctaHref?: T;
              images?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaSimpleCenteredGradient?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              id?: T;
              blockName?: T;
            };
        ctaSplitWithImage?:
          | T
          | {
              badge?: T;
              heading?: T;
              description?: T;
              ctaLabel?: T;
              ctaHref?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
              blockName?: T;
            };
        contactSimpleCentered?:
          | T
          | {
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    linkLabel?: T;
                    linkHref?: T;
                    iconSvg?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactSimpleFourCol?:
          | T
          | {
              title?: T;
              subtitle?: T;
              offices?:
                | T
                | {
                    name?: T;
                    lines?:
                      | T
                      | {
                          line?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactSplitWithForm?:
          | T
          | {
              heading?: T;
              description?: T;
              addressLabel?: T;
              addressHtml?: T;
              phoneLabel?: T;
              phoneText?: T;
              phoneHref?: T;
              emailLabel?: T;
              emailText?: T;
              emailHref?: T;
              formAction?: T;
              submitLabel?: T;
              id?: T;
              blockName?: T;
            };
        newsletterWithDetails?:
          | T
          | {
              heading?: T;
              description?: T;
              emailPlaceholder?: T;
              subscribeLabel?: T;
              features?:
                | T
                | {
                    iconSvg?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletterSimple?:
          | T
          | {
              heading?: T;
              emailPlaceholder?: T;
              subscribeLabel?: T;
              privacyText?: T;
              privacyLinkLabel?: T;
              privacyLinkHref?: T;
              id?: T;
              blockName?: T;
            };
        newsletterSimpleStacked?:
          | T
          | {
              heading?: T;
              emailPlaceholder?: T;
              subscribeLabel?: T;
              privacyText?: T;
              privacyLinkLabel?: T;
              privacyLinkHref?: T;
              id?: T;
              blockName?: T;
            };
        notFoundSimple?:
          | T
          | {
              errorCode?: T;
              heading?: T;
              description?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              id?: T;
              blockName?: T;
            };
        notFoundImageSplit?:
          | T
          | {
              companyName?: T;
              logoLight?: T;
              logoDark?: T;
              logoHref?: T;
              errorCode?: T;
              heading?: T;
              description?: T;
              backLabel?: T;
              backHref?: T;
              footerLinks?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              backgroundImageLight?: T;
              backgroundImageDark?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}